/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpacemanRouteImport } from './routes/spaceman'
import { Route as SlotpruebasRouteImport } from './routes/slotpruebas'
import { Route as SlotRouteImport } from './routes/slot'
import { Route as PayRouteImport } from './routes/pay'
import { Route as MinesRouteImport } from './routes/mines'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayBrebRouteImport } from './routes/pay_.breb'

const SpacemanRoute = SpacemanRouteImport.update({
  id: '/spaceman',
  path: '/spaceman',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotpruebasRoute = SlotpruebasRouteImport.update({
  id: '/slotpruebas',
  path: '/slotpruebas',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotRoute = SlotRouteImport.update({
  id: '/slot',
  path: '/slot',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const MinesRoute = MinesRouteImport.update({
  id: '/mines',
  path: '/mines',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBrebRoute = PayBrebRouteImport.update({
  id: '/pay_/breb',
  path: '/pay/breb',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dados': typeof DadosRoute
  '/home': typeof HomeRoute
  '/mines': typeof MinesRoute
  '/pay': typeof PayRoute
  '/slot': typeof SlotRoute
  '/slotpruebas': typeof SlotpruebasRoute
  '/spaceman': typeof SpacemanRoute
  '/pay/breb': typeof PayBrebRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dados': typeof DadosRoute
  '/home': typeof HomeRoute
  '/mines': typeof MinesRoute
  '/pay': typeof PayRoute
  '/slot': typeof SlotRoute
  '/slotpruebas': typeof SlotpruebasRoute
  '/spaceman': typeof SpacemanRoute
  '/pay/breb': typeof PayBrebRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dados': typeof DadosRoute
  '/home': typeof HomeRoute
  '/mines': typeof MinesRoute
  '/pay': typeof PayRoute
  '/slot': typeof SlotRoute
  '/slotpruebas': typeof SlotpruebasRoute
  '/spaceman': typeof SpacemanRoute
  '/pay_/breb': typeof PayBrebRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dados'
    | '/home'
    | '/mines'
    | '/pay'
    | '/slot'
    | '/slotpruebas'
    | '/spaceman'
    | '/pay/breb'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dados'
    | '/home'
    | '/mines'
    | '/pay'
    | '/slot'
    | '/slotpruebas'
    | '/spaceman'
    | '/pay/breb'
  id:
    | '__root__'
    | '/'
    | '/dados'
    | '/home'
    | '/mines'
    | '/pay'
    | '/slot'
    | '/slotpruebas'
    | '/spaceman'
    | '/pay_/breb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DadosRoute: typeof DadosRoute
  HomeRoute: typeof HomeRoute
  MinesRoute: typeof MinesRoute
  PayRoute: typeof PayRoute
  SlotRoute: typeof SlotRoute
  SlotpruebasRoute: typeof SlotpruebasRoute
  SpacemanRoute: typeof SpacemanRoute
  PayBrebRoute: typeof PayBrebRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spaceman': {
      id: '/spaceman'
      path: '/spaceman'
      fullPath: '/spaceman'
      preLoaderRoute: typeof SpacemanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slotpruebas': {
      id: '/slotpruebas'
      path: '/slotpruebas'
      fullPath: '/slotpruebas'
      preLoaderRoute: typeof SlotpruebasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slot': {
      id: '/slot'
      path: '/slot'
      fullPath: '/slot'
      preLoaderRoute: typeof SlotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mines': {
      id: '/mines'
      path: '/mines'
      fullPath: '/mines'
      preLoaderRoute: typeof MinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay_/breb': {
      id: '/pay_/breb'
      path: '/pay/breb'
      fullPath: '/pay/breb'
      preLoaderRoute: typeof PayBrebRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DadosRoute: DadosRoute,
  HomeRoute: HomeRoute,
  MinesRoute: MinesRoute,
  PayRoute: PayRoute,
  SlotRoute: SlotRoute,
  SlotpruebasRoute: SlotpruebasRoute,
  SpacemanRoute: SpacemanRoute,
  PayBrebRoute: PayBrebRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
