/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as TransaccionesRouteImport } from './routes/transacciones'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SpacemanRouteImport } from './routes/spaceman'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as SlotpruebasRouteImport } from './routes/slotpruebas'
import { Route as SlotRouteImport } from './routes/slot'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RuletaRouteImport } from './routes/ruleta'
import { Route as RetirosRouteImport } from './routes/retiros'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PayRouteImport } from './routes/pay'
import { Route as MisRecargasRouteImport } from './routes/mis-recargas'
import { Route as MinesRouteImport } from './routes/mines'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as DeportesRouteImport } from './routes/deportes'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as ChickenRouteImport } from './routes/chicken'
import { Route as BlackjackvipRouteImport } from './routes/blackjackvip'
import { Route as BlackjackRouteImport } from './routes/blackjack'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AdminpanelRouteImport } from './routes/adminpanel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayBrebRouteImport } from './routes/pay_.breb'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img.$'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const TransaccionesRoute = TransaccionesRouteImport.update({
  id: '/transacciones',
  path: '/transacciones',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacemanRoute = SpacemanRouteImport.update({
  id: '/spaceman',
  path: '/spaceman',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotpruebasRoute = SlotpruebasRouteImport.update({
  id: '/slotpruebas',
  path: '/slotpruebas',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotRoute = SlotRouteImport.update({
  id: '/slot',
  path: '/slot',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RuletaRoute = RuletaRouteImport.update({
  id: '/ruleta',
  path: '/ruleta',
  getParentRoute: () => rootRouteImport,
} as any)
const RetirosRoute = RetirosRouteImport.update({
  id: '/retiros',
  path: '/retiros',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const MisRecargasRoute = MisRecargasRouteImport.update({
  id: '/mis-recargas',
  path: '/mis-recargas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinesRoute = MinesRouteImport.update({
  id: '/mines',
  path: '/mines',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const DeportesRoute = DeportesRouteImport.update({
  id: '/deportes',
  path: '/deportes',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const ChickenRoute = ChickenRouteImport.update({
  id: '/chicken',
  path: '/chicken',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackjackvipRoute = BlackjackvipRouteImport.update({
  id: '/blackjackvip',
  path: '/blackjackvip',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackjackRoute = BlackjackRouteImport.update({
  id: '/blackjack',
  path: '/blackjack',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminpanelRoute = AdminpanelRouteImport.update({
  id: '/adminpanel',
  path: '/adminpanel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBrebRoute = PayBrebRouteImport.update({
  id: '/pay_/breb',
  path: '/pay/breb',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminpanel': typeof AdminpanelRoute
  '/arena': typeof ArenaRoute
  '/blackjack': typeof BlackjackRoute
  '/blackjackvip': typeof BlackjackvipRoute
  '/chicken': typeof ChickenRoute
  '/dados': typeof DadosRoute
  '/deportes': typeof DeportesRoute
  '/eventos': typeof EventosRoute
  '/home': typeof HomeRoute
  '/mines': typeof MinesRoute
  '/mis-recargas': typeof MisRecargasRoute
  '/pay': typeof PayRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retiros': typeof RetirosRoute
  '/ruleta': typeof RuletaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slot': typeof SlotRoute
  '/slotpruebas': typeof SlotpruebasRoute
  '/soporte': typeof SoporteRoute
  '/spaceman': typeof SpacemanRoute
  '/terminos': typeof TerminosRoute
  '/transacciones': typeof TransaccionesRoute
  '/vip': typeof VipRoute
  '/pay/breb': typeof PayBrebRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminpanel': typeof AdminpanelRoute
  '/arena': typeof ArenaRoute
  '/blackjack': typeof BlackjackRoute
  '/blackjackvip': typeof BlackjackvipRoute
  '/chicken': typeof ChickenRoute
  '/dados': typeof DadosRoute
  '/deportes': typeof DeportesRoute
  '/eventos': typeof EventosRoute
  '/home': typeof HomeRoute
  '/mines': typeof MinesRoute
  '/mis-recargas': typeof MisRecargasRoute
  '/pay': typeof PayRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retiros': typeof RetirosRoute
  '/ruleta': typeof RuletaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slot': typeof SlotRoute
  '/slotpruebas': typeof SlotpruebasRoute
  '/soporte': typeof SoporteRoute
  '/spaceman': typeof SpacemanRoute
  '/terminos': typeof TerminosRoute
  '/transacciones': typeof TransaccionesRoute
  '/vip': typeof VipRoute
  '/pay/breb': typeof PayBrebRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adminpanel': typeof AdminpanelRoute
  '/arena': typeof ArenaRoute
  '/blackjack': typeof BlackjackRoute
  '/blackjackvip': typeof BlackjackvipRoute
  '/chicken': typeof ChickenRoute
  '/dados': typeof DadosRoute
  '/deportes': typeof DeportesRoute
  '/eventos': typeof EventosRoute
  '/home': typeof HomeRoute
  '/mines': typeof MinesRoute
  '/mis-recargas': typeof MisRecargasRoute
  '/pay': typeof PayRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retiros': typeof RetirosRoute
  '/ruleta': typeof RuletaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slot': typeof SlotRoute
  '/slotpruebas': typeof SlotpruebasRoute
  '/soporte': typeof SoporteRoute
  '/spaceman': typeof SpacemanRoute
  '/terminos': typeof TerminosRoute
  '/transacciones': typeof TransaccionesRoute
  '/vip': typeof VipRoute
  '/pay_/breb': typeof PayBrebRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminpanel'
    | '/arena'
    | '/blackjack'
    | '/blackjackvip'
    | '/chicken'
    | '/dados'
    | '/deportes'
    | '/eventos'
    | '/home'
    | '/mines'
    | '/mis-recargas'
    | '/pay'
    | '/perfil'
    | '/ranking'
    | '/reset-password'
    | '/retiros'
    | '/ruleta'
    | '/sitemap.xml'
    | '/slot'
    | '/slotpruebas'
    | '/soporte'
    | '/spaceman'
    | '/terminos'
    | '/transacciones'
    | '/vip'
    | '/pay/breb'
    | '/api/public/img/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adminpanel'
    | '/arena'
    | '/blackjack'
    | '/blackjackvip'
    | '/chicken'
    | '/dados'
    | '/deportes'
    | '/eventos'
    | '/home'
    | '/mines'
    | '/mis-recargas'
    | '/pay'
    | '/perfil'
    | '/ranking'
    | '/reset-password'
    | '/retiros'
    | '/ruleta'
    | '/sitemap.xml'
    | '/slot'
    | '/slotpruebas'
    | '/soporte'
    | '/spaceman'
    | '/terminos'
    | '/transacciones'
    | '/vip'
    | '/pay/breb'
    | '/api/public/img/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/adminpanel'
    | '/arena'
    | '/blackjack'
    | '/blackjackvip'
    | '/chicken'
    | '/dados'
    | '/deportes'
    | '/eventos'
    | '/home'
    | '/mines'
    | '/mis-recargas'
    | '/pay'
    | '/perfil'
    | '/ranking'
    | '/reset-password'
    | '/retiros'
    | '/ruleta'
    | '/sitemap.xml'
    | '/slot'
    | '/slotpruebas'
    | '/soporte'
    | '/spaceman'
    | '/terminos'
    | '/transacciones'
    | '/vip'
    | '/pay_/breb'
    | '/api/public/img/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminpanelRoute: typeof AdminpanelRoute
  ArenaRoute: typeof ArenaRoute
  BlackjackRoute: typeof BlackjackRoute
  BlackjackvipRoute: typeof BlackjackvipRoute
  ChickenRoute: typeof ChickenRoute
  DadosRoute: typeof DadosRoute
  DeportesRoute: typeof DeportesRoute
  EventosRoute: typeof EventosRoute
  HomeRoute: typeof HomeRoute
  MinesRoute: typeof MinesRoute
  MisRecargasRoute: typeof MisRecargasRoute
  PayRoute: typeof PayRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RetirosRoute: typeof RetirosRoute
  RuletaRoute: typeof RuletaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlotRoute: typeof SlotRoute
  SlotpruebasRoute: typeof SlotpruebasRoute
  SoporteRoute: typeof SoporteRoute
  SpacemanRoute: typeof SpacemanRoute
  TerminosRoute: typeof TerminosRoute
  TransaccionesRoute: typeof TransaccionesRoute
  VipRoute: typeof VipRoute
  PayBrebRoute: typeof PayBrebRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacciones': {
      id: '/transacciones'
      path: '/transacciones'
      fullPath: '/transacciones'
      preLoaderRoute: typeof TransaccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaceman': {
      id: '/spaceman'
      path: '/spaceman'
      fullPath: '/spaceman'
      preLoaderRoute: typeof SpacemanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slotpruebas': {
      id: '/slotpruebas'
      path: '/slotpruebas'
      fullPath: '/slotpruebas'
      preLoaderRoute: typeof SlotpruebasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slot': {
      id: '/slot'
      path: '/slot'
      fullPath: '/slot'
      preLoaderRoute: typeof SlotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruleta': {
      id: '/ruleta'
      path: '/ruleta'
      fullPath: '/ruleta'
      preLoaderRoute: typeof RuletaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retiros': {
      id: '/retiros'
      path: '/retiros'
      fullPath: '/retiros'
      preLoaderRoute: typeof RetirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-recargas': {
      id: '/mis-recargas'
      path: '/mis-recargas'
      fullPath: '/mis-recargas'
      preLoaderRoute: typeof MisRecargasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mines': {
      id: '/mines'
      path: '/mines'
      fullPath: '/mines'
      preLoaderRoute: typeof MinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deportes': {
      id: '/deportes'
      path: '/deportes'
      fullPath: '/deportes'
      preLoaderRoute: typeof DeportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chicken': {
      id: '/chicken'
      path: '/chicken'
      fullPath: '/chicken'
      preLoaderRoute: typeof ChickenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blackjackvip': {
      id: '/blackjackvip'
      path: '/blackjackvip'
      fullPath: '/blackjackvip'
      preLoaderRoute: typeof BlackjackvipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blackjack': {
      id: '/blackjack'
      path: '/blackjack'
      fullPath: '/blackjack'
      preLoaderRoute: typeof BlackjackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminpanel': {
      id: '/adminpanel'
      path: '/adminpanel'
      fullPath: '/adminpanel'
      preLoaderRoute: typeof AdminpanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay_/breb': {
      id: '/pay_/breb'
      path: '/pay/breb'
      fullPath: '/pay/breb'
      preLoaderRoute: typeof PayBrebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminpanelRoute: AdminpanelRoute,
  ArenaRoute: ArenaRoute,
  BlackjackRoute: BlackjackRoute,
  BlackjackvipRoute: BlackjackvipRoute,
  ChickenRoute: ChickenRoute,
  DadosRoute: DadosRoute,
  DeportesRoute: DeportesRoute,
  EventosRoute: EventosRoute,
  HomeRoute: HomeRoute,
  MinesRoute: MinesRoute,
  MisRecargasRoute: MisRecargasRoute,
  PayRoute: PayRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RetirosRoute: RetirosRoute,
  RuletaRoute: RuletaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlotRoute: SlotRoute,
  SlotpruebasRoute: SlotpruebasRoute,
  SoporteRoute: SoporteRoute,
  SpacemanRoute: SpacemanRoute,
  TerminosRoute: TerminosRoute,
  TransaccionesRoute: TransaccionesRoute,
  VipRoute: VipRoute,
  PayBrebRoute: PayBrebRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
