/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpacemanRouteImport } from './routes/spaceman'
import { Route as PayRouteImport } from './routes/pay'
import { Route as MinesRouteImport } from './routes/mines'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'

const SpacemanRoute = SpacemanRouteImport.update({
  id: '/spaceman',
  path: '/spaceman',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const MinesRoute = MinesRouteImport.update({
  id: '/mines',
  path: '/mines',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/mines': typeof MinesRoute
  '/pay': typeof PayRoute
  '/spaceman': typeof SpacemanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/mines': typeof MinesRoute
  '/pay': typeof PayRoute
  '/spaceman': typeof SpacemanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/mines': typeof MinesRoute
  '/pay': typeof PayRoute
  '/spaceman': typeof SpacemanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home' | '/mines' | '/pay' | '/spaceman'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/mines' | '/pay' | '/spaceman'
  id: '__root__' | '/' | '/home' | '/mines' | '/pay' | '/spaceman'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  MinesRoute: typeof MinesRoute
  PayRoute: typeof PayRoute
  SpacemanRoute: typeof SpacemanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spaceman': {
      id: '/spaceman'
      path: '/spaceman'
      fullPath: '/spaceman'
      preLoaderRoute: typeof SpacemanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mines': {
      id: '/mines'
      path: '/mines'
      fullPath: '/mines'
      preLoaderRoute: typeof MinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  MinesRoute: MinesRoute,
  PayRoute: PayRoute,
  SpacemanRoute: SpacemanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
